# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2
defaults: &defaults
  docker:
    - image: circleci/node:8.9.3
  working_directory: ~/web-sdk
jobs:
  build-web-sdk:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Project Dependencies
          command: |
            yarn install --ignore-engines
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Build VatomInc-Web-SDK
          command: npm run build
      - persist_to_workspace:
         root: ~/web-sdk
         paths:
           - dist/*
           - node_modules/*
  publish-web-sdk:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/web-sdk
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/web-sdk/.npmrc
      - run:
          name: Publish package
          command: |
            npm publish --access public
workflows:
  version: 2
  build-web-sdk:
    jobs:
      - build-web-sdk
      - publish-web-sdk:
          requires:
            - build-web-sdk
          filters:
            branches:
              only: master